defaultSemverRangePrefix: ''

enableScripts: false

yarnPath: .yarn/releases/yarn-4.10.3.cjs
nodeLinker: node-modules

npmMinimalAgeGate: 10080

plugins:
  - path: .yarn/plugins/plugin-hh-fallback.cjs
