// Generates a registry of every custom error across our compiled contracts.
//
//   yarn compile                        # make sure artifacts are fresh
//   yarn docs:errors                    # writes ERRORS.md
//   yarn docs:errors 0x8d666f60         # look up a single selector
//
// Reads Hardhat artifacts under artifacts/contracts (our own contracts only).
// Inherited errors from dependencies (OpenZeppelin, Chainlink CCIP, ...) are
// still captured because Hardhat flattens them into each contract's ABI.
import { ethers } from 'ethers';

import { readdirSync, readFileSync, writeFileSync, statSync } from 'fs';
import { join } from 'path';

const repoRoot = join(__dirname, '..');
const artifactsDir = join(repoRoot, 'artifacts', 'contracts');
const outFile = join(repoRoot, 'ERRORS.md');

// Directory names to skip anywhere in the tree.
const skipDirs = new Set(['build-info', 'mocks', 'testers']);

const lookup = process.argv[2]?.toLowerCase();

type ErrorEntry = { signature: string; sources: Set<string> };

// Recursively collect artifact JSON files (skip debug + excluded dirs).
const walk = (dir: string): string[] => {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (skipDirs.has(entry)) continue;
      out.push(...walk(full));
    } else if (entry.endsWith('.json') && !entry.endsWith('.dbg.json')) {
      out.push(full);
    }
  }
  return out;
};

// selector -> { signature, sources }
const errors = new Map<string, ErrorEntry>();

for (const file of walk(artifactsDir)) {
  let artifact: { contractName?: string; abi?: unknown[] };
  try {
    artifact = JSON.parse(readFileSync(file, 'utf8'));
  } catch {
    continue;
  }
  if (!Array.isArray(artifact.abi)) continue;
  const contractName = artifact.contractName || file;

  let iface: ethers.utils.Interface;
  try {
    iface = new ethers.utils.Interface(artifact.abi as ethers.utils.Fragment[]);
  } catch {
    continue;
  }

  for (const signature of Object.keys(iface.errors)) {
    const selector = ethers.utils.id(signature).slice(0, 10);
    if (!errors.has(selector)) {
      errors.set(selector, { signature, sources: new Set() });
    }
    errors.get(selector)!.sources.add(contractName);
  }
}

if (lookup) {
  const hit = errors.get(lookup);
  if (hit) {
    console.log(`\n👉 ${lookup}  ${hit.signature}`);
    console.log(`   defined in: ${[...hit.sources].sort().join(', ')}`);
  } else {
    console.log(
      `\nNo error with selector ${lookup} found in ${errors.size} known errors.`,
    );
    console.log('Did you run `yarn compile` first?');
  }
  process.exit(hit ? 0 : 1);
}

const rows = [...errors.entries()]
  .map(([selector, { signature, sources }]) => ({
    selector,
    signature,
    sources: [...sources].sort().join(', '),
  }))
  .sort((a, b) => a.signature.localeCompare(b.signature));

const md = [
  '# Custom Errors',
  '',
  'Auto-generated by `scripts/generate-errors-readme.ts` from compiled artifacts.',
  `Total: ${rows.length} errors.`,
  '',
  '| Selector | Error | Declared in |',
  '| --- | --- | --- |',
  ...rows.map(
    (r) => `| \`${r.selector}\` | \`${r.signature}\` | ${r.sources} |`,
  ),
  '',
].join('\n');

writeFileSync(outFile, md);
console.log(`Wrote ${rows.length} errors to ${outFile}`);
